### ISSUE TITLE
cowfortune fails at random times due to wrong assumptions of available cowsay modules

### ISSUE THREAD

**Issue by UweKrause** [anthraxx/cowfortune#1]
Cowfortune makes some assumptions about the content (see 1) and the location (see 2) of the `/usr/share/cows` folder.

1.) this line tries to detect the available cowsay modules:
https://github.com/anthraxx/cowfortune/blob/baa36aef4e5edadd790fc21c210fa96c85b15544/cowfortune.sh#L34
When there are other files in the module folder than `.cow`, cowfortune tries sometimes to use those.
For example when there is a `.pm` file, cowfortune tries to use this filename as module for cowsay.

A wrong cow-module will lead to failing cowsay and therefore cowfortune:
```
cowsay: Can't locate Acme/Cow.pm in @INC (you may need to install the Acme::Cow module) (@INC contains: /usr/lib/perl5/5.32/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/5.32/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/5.32/core_perl /usr/share/perl5/core_perl) at /usr/share/cows/Stegosaurus.pm line 3, <STDIN> line 1.
BEGIN failed--compilation aborted at /usr/share/cows/Stegosaurus.pm line 3, <STDIN> line 1.
```

2.) 
It seems like the location of the cow-modules has changed (or is distro dependent?)
At least under arch linux, this path is wrong:
https://github.com/anthraxx/cowfortune/blob/baa36aef4e5edadd790fc21c210fa96c85b15544/cowfortune.sh#L8

---

**As solution for both, I recommend to "ask" cowsay for its available modules, instead of making assumptions.**
`cowsay -l`

Pull request incoming.

**Comment by ameeno** [comment]
good fix.
 I tried to use this script on my mac and had a few errors, not finding cows was one of them!!!!

the other error was the assumed cfgpath of /etc/cowsay and the assumed install path of /usr/bin.

both of those could be rectified with a change to the makefile, this change fixed the built script.

**Comment by anthraxx** [comment]
Oh i've missed this issue. Thanks for reporting, will release a fix :cat:

**Comment by dhruvhaldar** [comment]
I found this, might be helpful

https://perlmaven.com/cant-locate-in-inc

**Comment by UweKrause** [comment]
PR #2 already fixes the issue of not found modules.
I don't know if the second problem of @ameeno is related.
